### ISSUE TITLE
无法播放合集

### ISSUE THREAD

**Issue by huitengxile** [lovegaoshi/azusa-player#57]
Chrome 插件版本。
以 URL 搜索得到的合集，播放时一直卡在加载中，无法播放。
使用的URL为`https://space.bilibili.com/690261349/channel/collectiondetail?sid=1037280`

**Comment by lovegaoshi** [comment]
![image](https://github.com/lovegaoshi/azusa-player/assets/106490582/5b1a6cbd-9fc7-4f73-85e5-2148743ab811)
能放啊
