### ISSUE TITLE
手机版出现bug

### ISSUE THREAD

**Issue by ouguangye** [lovegaoshi/azusa-player#60]
桌面模式正常
![image](https://github.com/lovegaoshi/azusa-player/assets/78332649/402d0a5f-9fa9-441b-a6f9-626b0380c949)
但是当我使用F12切换到手机模式，刷新
![image](https://github.com/lovegaoshi/azusa-player/assets/78332649/820333b6-de22-44a7-97eb-344374e86970)
我使用手机安装狐猴浏览器，然后用这个浏览器安装该插件，也是白屏，切换到桌面模式就正常显示。

**Comment by lovegaoshi** [comment]
因为专门做了[手机端APP](https://github.com/lovegaoshi/azusa-player-mobile)，插件已经不支持手机咯
